**Question 1: Print all numbers from 10 to 99**

In [ ]:
for i in range(10,100):
    print(i)

**Question 2: Print whether a inputed number is single or double digit.**

In [ ]:
#Declaring Variables
playerInput = ""
valid = False

while valid == False:  #Will keep running until valid input is entered
    #Prompts User to enter input
    playerInput = eval(input("Please enter a number between 0 to 99: "))
    
    #Checks whether input is in desired range and correct type
    if str(type(playerInput)) == "<class 'int'>" and (playerInput > 99 or playerInput < 0):
        print("Your input is not in the correct range: ")
    else:  #If the input is valid it will calculate whether it is single or double digit and will break loop
        valid = True
        if len(str(playerInput)) == 1:
            print("single digit")

        else:
            print("double digit")

**Question 3: Print all even numbers from 10 to 99:**

In [ ]:
for i in range(10,100,2):
    print(i)

**Question 4: Print table of 5 from 5 to 50**

In [ ]:
for i in range(5, 51, 5):
    print(i)

**Question 5: Print table of fives from 5 to 50 but show which multiples can be divided by three.**

In [ ]:
for i in range(5, 51, 5):
    if i%3==0:
        print(i,"can be divided by three")
    else:
        print(i)


1.   **Question 6A: how would you fix this code?**

2.   **Question 6B: how would you fix this code?** 

*   **Answer 6A: In Document**
*   **Answer 6B: In Document**

**Question 7: You have the below list-print all the elements from this list.**

In [ ]:
prices = [10, 130, 25, 64, 91, 66, 42, 18, 141, 64]


for i in prices:
    print(i)

**Question 8: Filter all numbers above 20 and below 80 in given list:**

In [48]:
prices = [10,130,25, 64,91,66,42,18,141,64]
filtered_list = []

for i in prices:
    if i > 20 and i < 80:
        filtered_list.append(i)
    else:
        pass

print(filtered_list)

[25, 64, 66, 42, 64]

**Question 9:
Write a program  that accepts a username and a password from the user. If the username entered is “student007” and password entered is “new_password”, your program should print a message “Login successful”. Otherwise it should print a message “Try again. Login failure”.**

In [ ]:
USERNAME = "student007"
PASSWORD = "new_password"

playerInputUserName = input("Enter username: ")
playerInputUserPassword = input("Enter password: ")

if playerInputUserName == USERNAME and playerInputUserPassword == PASSWORD:
    print("Login Successful")
else:
    print("Try again, login failed")

**Question 10:
Write a program to accept a username from the user. If the length of the username is less than 5 or if the length of the username is greater than 16, your program should print “Invalid username”. Otherwise your program should print the message “valid username”.**

In [ ]:
MAX = 16
MIN = 5

PlayerInput = input("Enter username: ")

if MIN>len(PlayerInput) or len(PlayerInput)>MAX:
    print("Invalid username")
else:
    print("Valid username")

**Challenge Question 1 (Extra Credit): You have a list of prices of items in a store. Write a program that prints all pairs of items that add up to 50. Your program should print the output as follows (Not Achieved)**

**Challenge Question 2 (Extra Credit): Write a program to search a name in a list of names. If the name is found, print the message “name found: <name>”. Otherwise print name not found. Use the above list of names in your code.(Achieved)**

In [49]:
names = ["sarang","john","lily","jasmine","mara","dave","chester"]
searchNameInput = input("Enter name you want to search: ").lower()
found = False
for i in names:
    if i == searchNameInput:
        found = True
        print("Name found:",searchNameInput)
        break

if found == False:
    print ("Name not found:", searchNameInput)

Enter name you want to search: saran
Name not found: saran

In [51]:
for i in range(10,99,3):
    print(i)

10
13
16
19
22
25
28
31
34
37
40
43
46
49
52
55
58
61
64
67
70
73
76
79
82
85
88
91
94
97